feat: Accordion and general styling.
scania-digital-design-system/tegel-angular-demo pull request #6
Opened 2023-07-28 15:39 UTC by timrombergjakobsson

2023-07-31 12:36 UTC, theJohnnyMe commented
@timrombergjakobsson  - There seems to be an issue with the Netlify build. Please check "Latest deploy log".

2023-07-31 12:45 UTC, theJohnnyMe requested changes

2023-07-31 12:45 UTC, theJohnnyMe commented on src/app/app.component.css
> +@import url('@scania/tegel/dist/tegel/tegel.css');
This is already imported in "styles.css".

2023-07-31 12:45 UTC, theJohnnyMe commented on src/app/app.component.css
> +@import url('https://cdn.digitaldesign.scania.com/icons/webfont/css/sdds-icons.css');
Is this needed? 
Our icons come as a web-component now, so no need to import anything related to SDDS code.
Please double-check.

2023-07-31 15:11 UTC, theJohnnyMe requested changes

2023-08-01 06:41 UTC, timrombergjakobsson commented on src/app/accordion-item/accordion-item.component.html
> +<div [class.expanded]="expanded">
No, your right, was a piece of old code that was to be removed. Missed it.

2023-08-01 07:05 UTC, theJohnnyMe approved these changes
Nice work buddy!

2023-08-01 07:09 UTC, merged